// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njctylnnplnisgwddnyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qY3R5bG5ucGxuaXNnd2RkbnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjg1NTYsImV4cCI6MjA3Mjk0NDU1Nn0.O2SRLJryosrDQ6qsadS4XqbKnz0QHr4GzdS2nq3PmHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});